### PR TITLE
[QA-331] Adding shared memory method to file copy

### PR DESCRIPTION
**Pull request by Aleksandras-V**
To try the shared memory method use:
    - `ipc_receivefile --shm --file <your dest file>`
    - `ipc_sendfile --shm --file <your source file>`

### CODE REVIEW

**Comment by baovu-unikie** [comment]
Hi, 
In this branch (`devel/shmem`), the Makefile is not completed. I can't run `make` command.
image

**Comment by Aleksandras-V** [comment]
> Hi, In this branch (`devel/shmem`), the Makefile is not completed. I can't run `make` command. image

Yes, the problem is that if I put the qcc place and the export variables it will be only for my environment, you will have to adapt it to yours anyways, but does it work on the IDE ?

**Comment by Aleksandras-V** [comment]
> 

Try now, I modified it.

**Comment by baovu-unikie** [comment]
I pull the newest commit. Compiling is ok now. 
image
But there is an error when run ipc_receivefile
image

**Comment by Aleksandras-V** [comment]
> I pull the newest commit. Compiling is ok now. image But there is an error when run ipc_receivefile image

is your file "lala" existing? In my program both receive and send file needs to exist

**Comment by baovu-unikie** [comment]
It runs OK now (I created lala file), but if I change the order of arguments it won't work.

**Review by baovu-unikie — APPROVED** [review]

**Comment by Aleksandras-V** [comment]
> ut if I change the order of arguments it won't work.

Did you tried, I think it should work !

**Comment by baovu-unikie** [comment]
> > ut if I change the order of arguments it won't work.
> 
> Did you tried, I think it should work !

image
I did try.

**Comment by Aleksandras-V** [comment]
> > > ut if I change the order of arguments it won't work.
> > 
> > 
> > Did you tried, I think it should work !
> 
> image I did try.

And what happened ?

**Comment by Aleksandras-V** [comment]
> > > ut if I change the order of arguments it won't work.
> > 
> > 
> > Did you tried, I think it should work !
> 
> image I did try.

Try now !

**Comment by baovu-unikie** [comment]
It's working now :D

**Review by maksim-estonia — APPROVED** [review]
Everything works

**Pull request merged**
